### PR TITLE
Build/android and ios

### PR DESCRIPTION
**Pull request by berendsliedrecht**
- build multi architecture library for Android
- build xcframework for iOS

### CODE REVIEW

**Comment by berendsliedrecht** [comment]
Copied mostly from indr-vdr

**Comment by TimoGlastra** [comment]
Doesn't this need the docker files to build? Is that because of zmq?

**Review by TimoGlastra — APPROVED** [review]

**Comment by TimoGlastra** [comment]
Master is behind quite a bit, might be good to update it first

**Comment by berendsliedrecht** [comment]
> Doesn't this need the docker files to build? Is that because of zmq?

Yeah it can use the default images provided by Cross.

**Pull request merged**
